# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lightsage < Formula
  desc "Manage Lightsage visibility, prompts, evals, content, and tasks"
  homepage "https://lightsage.com/docs"
  version "0.6.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lightsagehq/homebrew-tools/releases/download/v0.6.7/lightsage_Darwin_x86_64.tar.gz"
      sha256 "a5c35a4e8364eb51e599224ad1a78bb80733d22e94cf81fa2d190fbd6c626eff"

      def install
        bin.install "lightsage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lightsagehq/homebrew-tools/releases/download/v0.6.7/lightsage_Darwin_arm64.tar.gz"
      sha256 "bfae4b6fc1a4d6058adfc17cbd20de6ab32456347463fe079eeee2a142ee5c91"

      def install
        bin.install "lightsage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/lightsagehq/homebrew-tools/releases/download/v0.6.7/lightsage_Linux_x86_64.tar.gz"
      sha256 "6007ce21afef6900969a40f933482faa5bf19cc6dbd7ee24cd25b0ca4828eafb"
      def install
        bin.install "lightsage"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/lightsagehq/homebrew-tools/releases/download/v0.6.7/lightsage_Linux_arm64.tar.gz"
      sha256 "6660a5c4bb75edfc9e770aa2fff21bbd609abceb71da78cf7855e0b37c094538"
      def install
        bin.install "lightsage"
      end
    end
  end

  test do
    system "#{bin}/lightsage", "version"
  end
end
